version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebJFBM
    container_name: frontendJFBM

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendJFBM
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebJFBM
    container_name: backendJFBM

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebJFBM
    ports:
      - "80:80" # si tienes problemas con el puerto 80 cambia el puerto externo aquí
    networks:
      - redwebJFBM
    container_name: webJFBM

networks:
  redwebJFBM:
    driver: bridge
